/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ProductDAO.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Classify service. Represents a row in the &quot;GK_Classify&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>ProductDAO.model.impl.ClassifyModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>ProductDAO.model.impl.ClassifyImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Classify
 * @generated
 */
@ProviderType
public interface ClassifyModel extends BaseModel<Classify> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a classify model instance should use the {@link Classify} interface instead.
	 */

	/**
	 * Returns the primary key of this classify.
	 *
	 * @return the primary key of this classify
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this classify.
	 *
	 * @param primaryKey the primary key of this classify
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the classify ID of this classify.
	 *
	 * @return the classify ID of this classify
	 */
	public long getClassifyId();

	/**
	 * Sets the classify ID of this classify.
	 *
	 * @param ClassifyId the classify ID of this classify
	 */
	public void setClassifyId(long ClassifyId);

	/**
	 * Returns the classify name of this classify.
	 *
	 * @return the classify name of this classify
	 */
	@AutoEscape
	public String getClassifyName();

	/**
	 * Sets the classify name of this classify.
	 *
	 * @param classifyName the classify name of this classify
	 */
	public void setClassifyName(String classifyName);

	@Override
	public Classify cloneWithOriginalValues();

}