/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ProductDAO.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the GKDetail service. Represents a row in the &quot;GK_GKDetail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>ProductDAO.model.impl.GKDetailModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>ProductDAO.model.impl.GKDetailImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GKDetail
 * @generated
 */
@ProviderType
public interface GKDetailModel extends BaseModel<GKDetail> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a gk detail model instance should use the {@link GKDetail} interface instead.
	 */

	/**
	 * Returns the primary key of this gk detail.
	 *
	 * @return the primary key of this gk detail
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this gk detail.
	 *
	 * @param primaryKey the primary key of this gk detail
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the gk detail ID of this gk detail.
	 *
	 * @return the gk detail ID of this gk detail
	 */
	public long getGKDetailId();

	/**
	 * Sets the gk detail ID of this gk detail.
	 *
	 * @param GKDetailId the gk detail ID of this gk detail
	 */
	public void setGKDetailId(long GKDetailId);

	/**
	 * Returns the g knumber of this gk detail.
	 *
	 * @return the g knumber of this gk detail
	 */
	@AutoEscape
	public String getGKnumber();

	/**
	 * Sets the g knumber of this gk detail.
	 *
	 * @param GKnumber the g knumber of this gk detail
	 */
	public void setGKnumber(String GKnumber);

	/**
	 * Returns the norm of this gk detail.
	 *
	 * @return the norm of this gk detail
	 */
	@AutoEscape
	public String getNorm();

	/**
	 * Sets the norm of this gk detail.
	 *
	 * @param norm the norm of this gk detail
	 */
	public void setNorm(String norm);

	/**
	 * Returns the gk name of this gk detail.
	 *
	 * @return the gk name of this gk detail
	 */
	@AutoEscape
	public String getGKName();

	/**
	 * Sets the gk name of this gk detail.
	 *
	 * @param GKName the gk name of this gk detail
	 */
	public void setGKName(String GKName);

	/**
	 * Returns the pre order of this gk detail.
	 *
	 * @return the pre order of this gk detail
	 */
	@AutoEscape
	public String getPreOrder();

	/**
	 * Sets the pre order of this gk detail.
	 *
	 * @param preOrder the pre order of this gk detail
	 */
	public void setPreOrder(String preOrder);

	/**
	 * Returns the gk component of this gk detail.
	 *
	 * @return the gk component of this gk detail
	 */
	@AutoEscape
	public String getGKComponent();

	/**
	 * Sets the gk component of this gk detail.
	 *
	 * @param GKComponent the gk component of this gk detail
	 */
	public void setGKComponent(String GKComponent);

	/**
	 * Returns the freight of this gk detail.
	 *
	 * @return the freight of this gk detail
	 */
	@AutoEscape
	public String getFreight();

	/**
	 * Sets the freight of this gk detail.
	 *
	 * @param freight the freight of this gk detail
	 */
	public void setFreight(String freight);

	/**
	 * Returns the price of this gk detail.
	 *
	 * @return the price of this gk detail
	 */
	public int getPrice();

	/**
	 * Sets the price of this gk detail.
	 *
	 * @param price the price of this gk detail
	 */
	public void setPrice(int price);

	/**
	 * Returns the team of this gk detail.
	 *
	 * @return the team of this gk detail
	 */
	@AutoEscape
	public String getTeam();

	/**
	 * Sets the team of this gk detail.
	 *
	 * @param team the team of this gk detail
	 */
	public void setTeam(String team);

	/**
	 * Returns the remark of this gk detail.
	 *
	 * @return the remark of this gk detail
	 */
	@AutoEscape
	public String getRemark();

	/**
	 * Sets the remark of this gk detail.
	 *
	 * @param remark the remark of this gk detail
	 */
	public void setRemark(String remark);

	/**
	 * Returns the image name of this gk detail.
	 *
	 * @return the image name of this gk detail
	 */
	@AutoEscape
	public String getImageName();

	/**
	 * Sets the image name of this gk detail.
	 *
	 * @param imageName the image name of this gk detail
	 */
	public void setImageName(String imageName);

	/**
	 * Returns the total of this gk detail.
	 *
	 * @return the total of this gk detail
	 */
	public int getTotal();

	/**
	 * Sets the total of this gk detail.
	 *
	 * @param total the total of this gk detail
	 */
	public void setTotal(int total);

	@Override
	public GKDetail cloneWithOriginalValues();

}